/**
 * Pulls a lead photo for each club from Wikipedia/Wikimedia (freely licensed),
 * keeping only confident title matches. Writes frontend/src/clubImages.js.
 * Clubs without a confident match keep the designed gradient cover.
 *   node fetchClubImages.js
 */
const axios = require("axios");
const fs = require("fs");
const path = require("path");
const UA = "thedjrankings/1.0 (https://thedjrankings.com)";
const norm = s => (s || "").normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase().replace(/[^a-z0-9]/g, "");

// [club name, city, optional explicit Wikipedia title]
const CLUBS = [
  ["Club Space", "Miami"], ["Amnesia", "Ibiza", "Amnesia (nightclub)"], ["Berghain / Panorama Bar", "Berlin", "Berghain"],
  ["DC-10", "Ibiza"], ["Tresor", "Berlin", "Tresor (club)"], ["Sub Club", "Glasgow", "Sub Club"], ["fabric", "London", "Fabric (club)"],
  ["Robert Johnson", "Offenbach", "Robert Johnson (club)"], ["Smart Bar", "Chicago", "Smartbar"], ["Rex Club", "Paris", "Rex Club"],
  ["Bassiani", "Tbilisi", "Bassiani (nightclub)"], ["Stereo", "Montreal"], ["The Block", "Tel Aviv"], ["Concrete", "Paris", "Concrete (nightclub)"],
  ["Watergate", "Berlin", "Watergate (club)"], ["Lux Frágil", "Lisbon", "Lux Frágil"], ["Nowadays", "Queens"], ["://about blank", "Berlin", "About Blank (club)"],
  ["Sisyphos", "Berlin", "Sisyphos (club)"], ["Fuse", "Brussels", "Fuse (nightclub)"], ["Khidi", "Tbilisi"], ["De School", "Amsterdam", "De School (nightclub)"],
  ["Corsica Studios", "London", "Corsica Studios"], ["Nitsa", "Barcelona", "Sala Apolo"], ["Tenax", "Florence", "Tenax (nightclub)"],
  ["Kompass Klub", "Ghent"], ["Basement", "Queens"], ["D-Edge", "São Paulo", "D-Edge"], ["Womb", "Tokyo", "Womb (nightclub)"],
  ["Kater Blau", "Berlin", "Kater Blau"], ["Shelter", "Amsterdam"], ["Warehouse Project", "Manchester", "The Warehouse Project"],
  ["FOLD", "London"], ["Cocoricò", "Riccione", "Cocoricò"], ["Goa", "Madrid", "Goa (nightclub)"], ["Razzmatazz", "Barcelona", "Razzmatazz (nightclub)"],
  ["RSO", "Berlin"], ["Bossa Nova Civic Club", "Brooklyn"], ["Vent", "Tokyo"], ["Warung Beach Club", "Itajaí", "Warung Beach Club"],
  ["Phonox", "London", "Phonox"], ["Public Records", "Brooklyn"], ["Halcyon", "San Francisco"], ["Flash", "Washington"],
  ["La Cheetah", "Glasgow"], ["Bloc", "London", "Bloc (organisation)"], ["Spazio 900 / Goa Roma", "Rome", "Goa (club)"],
  ["Salon zur Wilden Renate", "Berlin"], ["Pacha", "Ibiza", "Pacha (nightclub)"], ["Hï Ibiza", "Ibiza", "Hï Ibiza"],
];

async function pageImage(title) {
  const r = await axios.get("https://en.wikipedia.org/w/api.php", {
    params: { action: "query", format: "json", prop: "pageimages", piprop: "original", titles: title, redirects: 1 },
    headers: { "User-Agent": UA }, timeout: 12000,
  });
  const pages = r.data?.query?.pages || {};
  const p = Object.values(pages)[0];
  return p && p.original ? { title: p.title, url: p.original.source } : null;
}

async function searchImage(name, city) {
  const r = await axios.get("https://en.wikipedia.org/w/api.php", {
    params: { action: "query", format: "json", prop: "pageimages", piprop: "original",
      generator: "search", gsrlimit: 1, gsrsearch: `${name} ${city} nightclub` },
    headers: { "User-Agent": UA }, timeout: 12000,
  });
  const pages = r.data?.query?.pages || {};
  const p = Object.values(pages)[0];
  return p && p.original ? { title: p.title, url: p.original.source } : null;
}

(async () => {
  const out = {};
  let hits = 0;
  for (const [name, city, title] of CLUBS) {
    let res = null, trusted = false;
    try {
      if (title) { res = await pageImage(title); if (res) trusted = norm(res.title) === norm(title); }
      if (!res) res = await searchImage(name, city);
    } catch {}
    // Trust a curated exact-title hit; otherwise the resolved article title must
    // contain the club's base name (no city fallback — it matched city articles).
    const base = norm(name.split("/")[0].replace(/\b(club|nightclub|beach|civic|studios)\b/gi, ""));
    const nameMatch = res && base.length >= 4 && norm(res.title).includes(base);
    const ok = res && (trusted || nameMatch);
    if (res && ok && /\.(jpg|jpeg|png)$/i.test(res.url)) {
      out[name] = res.url; hits++;
      console.log(`  ✓ ${name} → ${res.title}`);
    } else {
      console.log(`  · ${name} → ${res ? "low-confidence (" + res.title + ")" : "no image"} (gradient fallback)`);
    }
    await new Promise(r => setTimeout(r, 150));
  }
  const dest = path.join(__dirname, "..", "frontend", "src", "clubImages.js");
  fs.writeFileSync(dest, "// Auto-generated by backend/fetchClubImages.js — Wikimedia lead images (freely licensed).\n// Clubs without a confident match use the designed gradient cover.\nexport const CLUB_IMAGES = " + JSON.stringify(out, null, 2) + ";\n");
  console.log(`\n${hits}/${CLUBS.length} clubs matched a Wikimedia photo → frontend/src/clubImages.js`);
})();
