// Rich editorial profiles for the Club Index. Curated lore — engaging, opinionated,
// and unafraid of the edgy stuff. Fields: capacity, founded (context), residencies,
// lore, iconicSets[], unique, reputation, secrets. Clubs without an entry fall back
// to their one-line note + criteria breakdown on the profile page.
export const CLUB_PROFILES = {
  "Club Space": {
    capacity: "≈ 1,500 (multi-room + open-air Terrace)", founders: "Louis Puig",
    residencies: "Link Miami Rebels · Saturday sunrise sets",
 lore: "Born in 2000 in a downtown Miami warehouse district nobody else wanted, Space pioneered the American 24-hour license and turned the after-hours marathon into an art form. Its open-air Terrace at dawn, palms, skyline, sweat and a sunrise that hits as the kick keeps rolling, is the single most romanticized room in US dance music.",
    iconicSets: [
 "Danny Tenaglia's marathon all-nighters in the 2000s: sometimes 12+ hours solo, the stuff of NYC/Miami legend.",
      "The Martinez Brothers and Solomun closing the Terrace at sunrise during Miami Music Week.",
      "Ceviche/Link Miami Rebels dawn sets where the booth doesn't stop until the security guards beg.",
    ],
 unique: "The Terrace sunrise. No other major US club is built around playing through the night into open-air daylight, it weaponizes time and the Miami sky.",
 reputation: "The US after-hours mecca. Revered by DJs as a place where the crowd actually came to dance, not to be seen, though Miami Music Week has made the doors a circus every March.",
 secrets: "Resident DJs are notorious for ignoring set-time 'limits', sunrise sets routinely blow past noon. The Terrace's sound and the moment the roof opens to daylight are deliberately timed to peak with the sun.",
  },
  "Amnesia": {
    capacity: "≈ 5,000 (two rooms)", founders: "Originally a finca; reborn as a club in 1976",
    residencies: "Cocoon (Sven Väth) · Pyramid · Música On (Marco Carola)",
 lore: "It started as an open-air farmhouse where freaks, hippies and the early Balearic crowd danced under the stars: no roof, just Ibiza. When noise laws forced a roof on in the '90s, the trapped heat created the legendary 'sweat' and the famous ice-cannons and foam. Sven Väth's Cocoon turned it into the global capital of techno Mondays for two decades.",
    iconicSets: [
 "Sven Väth's Cocoon openings and closings: era-defining, often pushing 8–10 hours.",
      "Alfredo's Balearic sets in the '80s that shaped the entire 'Ibiza sound' and inspired UK acid house.",
      "Marco Carola's Música On marathons that ran from midnight deep into the next afternoon.",
    ],
    unique: "Balearic ground zero. The DNA of modern dance music's 'anything goes' mixing was forged on this dancefloor before it ever reached London or Berlin.",
 reputation: "Heritage incarnate, the most historically important club on the island. Purists grumble it's grown commercial, but its place in the canon is untouchable.",
 secrets: "The roof was only added because of noise complaints, the original magic was the open sky. The ice cannons exist because the enclosed room got dangerously hot once it was sealed.",
  },
  "Berghain / Panorama Bar": {
    capacity: "≈ 1,500", founders: "Norbert Thormann & Michael Teufele (from Ostgut)",
    residencies: "Klubnacht (Sat→Mon) · Panorama Bar house upstairs · Lab.oratory",
 lore: "Housed in a monolithic former East German power plant, Berghain is the most mythologized nightclub on earth. The weekend doesn't end, Klubnacht runs Saturday night clear into Monday morning. The door, run by the inscrutable Sven Marquardt, is the most famous bouncer's-decision in nightlife: no logic published, no appeals, no photos inside ever.",
    iconicSets: [
 "Marcel Dettmann and Ben Klock defining the 'Berghain sound': relentless, hypnotic, monochrome techno.",
      "Panorama Bar Sunday-afternoon house sets where the blinds famously crack open to let daylight in for a few seconds.",
      "Fischerspooner, and countless 12-hour closing sets that have become scene folklore.",
    ],
 unique: "Time and secrecy. Stickered phone cameras, no documentation, a 60-hour weekend: it engineers a present-tense, anything-is-permitted freedom no other club matches.",
 reputation: "The undisputed global benchmark for credibility and hedonism, a techno cathedral with a legendary dark room (Lab.oratory) and a door that rejects the famous as readily as the unknown.",
 secrets: "Phone cameras are taped over at the door so nothing leaves the building. The brief moment Panorama Bar's window blinds open on Sunday, flooding the floor with daylight, is one of the most quietly euphoric rituals in clubbing.",
  },
  "DC-10": {
    capacity: "≈ 1,500 (Terrace + Main)", founders: "Circoloco party since 1999",
    residencies: "Circoloco (Mondays)",
 lore: "Wedged beside the Ibiza airport runway with planes screaming overhead, DC-10 began as an illegal-feeling Monday after-party and became the island's last bastion of no-VIP, no-frills hedonism. The Terrace, low ceiling, open sides, sweat dripping from above, is where the underground goes when the rest of Ibiza turns into a bottle-service theme park.",
    iconicSets: [
      "Circoloco Mondays that launched the careers of Seth Troxler, the Martinez Brothers, tINI and the whole modern Terrace generation.",
      "Jamie Jones / Hot Creations Terrace takeovers that defined a decade of tech-house.",
 "Daytime-into-night sets with planes landing meters away, chaos and euphoria in equal measure.",
    ],
    unique: "No VIP culture, planes overhead, the Terrace. It deliberately rejects the glamour the rest of Ibiza sells.",
 reputation: "The credible heart of Ibiza: raw, sweaty, anti-glamour. Has had its run-ins with the law (a famous 2008 police raid) which only burnished the outlaw mystique.",
 secrets: "There used to be effectively no proper sound treatment on the Terrace, the rawness was the point. The 2008 raid that briefly shut it down is now worn as a badge of honor.",
  },
  "Tresor": {
    capacity: "≈ 1,000", founders: "Dimitri Hegemann",
    residencies: "Tresor label nights · Globus (house upstairs)",
    lore: "Opened in 1991 in the vault of a bombed-out department store in the death strip between East and West Berlin, Tresor literally built techno in the rubble of the Cold War. DJs played behind the old bank's steel safe-deposit bars, fog so thick you couldn't see the booth. It forged the Detroit–Berlin axis that defines techno to this day.",
    iconicSets: [
      "Jeff Mills and Blake Baxter bringing Detroit techno straight into the vault in the early '90s.",
 "Juan Atkins' long association, the Detroit founders treated Tresor as their European home.",
      "The original vault closing party in 2005 before its move to the current power-plant location.",
    ],
 unique: "It was born in the literal no-man's-land of a just-fallen wall, techno as reunification soundtrack. The steel-vault room is unrepeatable history.",
    reputation: "The most historically foundational techno club in the world; the label is as important as the venue. Less fashionable than Berghain now, but the bloodline runs through it.",
 secrets: "The original space was an actual bank vault, dancers were boxed in by safe-deposit boxes. The fog was famously so heavy it was part of the disorienting magic.",
  },
  "Sub Club": {
    capacity: "≈ 410", founders: "Opened 1987",
    residencies: "Subculture (Harri & Domenic, since 1994) · Optimo heritage",
 lore: "Under the railway arches of Glasgow's Jamaica Street, the Sub Club is the longest continuously running underground dance club on the planet. Tiny, low-ceilinged and famously loud, 'Subbie' survived a devastating 1999 fire that closed it for years, and the city's devotion brought it back. Subculture with Harri & Domenic has run weekly since 1994.",
    iconicSets: [
 "Harri & Domenic's Subculture residency, one of the longest-running weekly house nights in the world.",
      "Optimo (JD Twitch & JG Wilkes) Sunday nights that became internationally mythologized for genre-melting sets.",
      "Daft Punk and countless legends playing the sweatbox before they were arena acts.",
    ],
    unique: "Longevity and intimacy. A ~410-capacity arch that has out-survived every trend since 1987, with a sound system worshipped by purists.",
 reputation: "Scotland's beating heart and a global underground pilgrimage: proof that small, consistent and music-first beats big and shiny every time.",
    secrets: "A 1999 fire in the building next door shut it for years; the scene never let it die. The low ceiling and the Subbie sound system are spoken about in near-religious terms.",
  },
  "fabric": {
    capacity: "≈ 1,600 (three rooms)", founders: "Keith Reilly & Cameron Leslie",
    residencies: "fabriclive heritage · the FABRIC mix series",
 lore: "Opened 1999 in a former Smithfield meat cold-store, fabric's Room One is built on a 'bodysonic' floor, bass transducers under the dancefloor so you feel the low end through your feet. Its mix CD series became the most respected in the world. In 2016 a licensing battle briefly shut it down; a global outcry and £300k crowdfund forced London to reverse course, a landmark moment for nightlife rights.",
    iconicSets: [
      "Craig Richards & Terry Francis' founding residencies that set the musical compass.",
      "Ricardo Villalobos' legendary marathon Room One sessions.",
      "Countless fabric/fabriclive mix recordings that defined careers (Ricardo, Omar-S, Goldie).",
    ],
 unique: "The bodysonic Room One floor: you don't just hear the bass, the dancefloor vibrates it into your body.",
    reputation: "London's flagship and a symbol of the fight for clubbing's survival. The 2016 closure-and-reversal made it a cause célèbre for nightlife everywhere.",
    secrets: "The vibrating floor is genuinely engineered (bass transducers), not a myth. The building is a converted Victorian meat cold-store, which is why the layout is a warren.",
  },
  "Robert Johnson": {
    capacity: "≈ 300", founders: "Ata Macias",
    residencies: "Live at Robert Johnson (label)",
 lore: "A small, almost featureless white room on the Main river in unfashionable Offenbach, Robert Johnson punches absurdly above its size. No frills, no spectacle: just a perfect floor, a sublime sound system, and a curatorial taste so sharp that its Live at Robert Johnson label became one of the most respected in dance music.",
    iconicSets: [
      "Ata and the Playhouse/Ongaku crew sets that shaped a distinctly Frankfurt sound.",
      "Gerd Janson's tastemaking nights and the broader Running Back family.",
      "Long, deep, no-photos sessions where the room's intimacy is the whole point.",
    ],
    unique: "Maximal influence from a minimal room. ~300 capacity, near-zero decor, world-class taste and sound.",
 reputation: "A DJ's-DJ temple, the room serious selectors name when asked their favorite. Quiet, precise, deeply credible.",
    secrets: "The riverside balcony is the unofficial heart of the night. Its label, not just the venue, is half the reason for its outsized reputation.",
  },
  "Smart Bar": {
    capacity: "≈ 400", founders: "Joe Shanahan",
    residencies: "Queen! · Resident DJ program",
 lore: "Beneath the Metro in Chicago since 1982, Smart Bar is the hometown room of house music itself. While the genre was being born blocks away at the Warehouse and Music Box, Smart Bar gave it a permanent basement home, and it never sold out. Decades on, it still treats house and techno with hometown reverence.",
    iconicSets: [
 "Frankie Knuckles, the Godfather of House, held a residency here; the city later named a street after him.",
      "Derrick Carter and the Chicago house royalty as regular fixtures.",
      "Queen!, the long-running queer house party keeping the dancefloor's roots alive.",
    ],
 unique: "It's house music's literal hometown club, an unbroken line back to the genre's Chicago birth.",
    reputation: "Sacred ground for anyone who reveres house's origins. Unpretentious, deep, and proudly local.",
 secrets: "Frankie Knuckles' connection runs deep, Chicago honored him with 'Frankie Knuckles Way.' The club has resisted commercialization for 40+ years on principle.",
  },
  "Rex Club": {
    capacity: "≈ 600", founders: "Opened 1988",
    residencies: "Laurent Garnier's long association",
    lore: "Paris's techno bedrock since 1988, the Rex is where Laurent Garnier made his name and France discovered the machine music. Famous for one of the best club sound systems in Europe (a custom rig obsessed over for decades), it's the room that legitimized electronic music in a city that took its time embracing it.",
    iconicSets: [
 "Laurent Garnier's legendary multi-hour Rex sets, foundational to French techno.",
      "Jeff Mills and the Detroit axis treating Rex as their Paris home.",
      "The Automatik nights that defined Parisian techno for a generation.",
    ],
    unique: "A sound system Parisians speak of in hushed tones, and the venue that single-handedly made techno respectable in France.",
 reputation: "France's most important techno institution: serious, sound-obsessed, and historically central.",
    secrets: "The custom sound rig has been tweaked and worshipped for 30+ years. Garnier's history here is so deep the club is almost synonymous with him.",
  },
  "Bassiani": {
    capacity: "≈ 1,200", founders: "Tato Getia & Zviad Gelbakhiani",
    residencies: "Horoom Nights (queer party) · Bassiani residents",
 lore: "Built into a drained Soviet-era swimming pool beneath Tbilisi's national football stadium, Bassiani is techno as resistance. In a conservative post-Soviet society, it became a sanctuary, especially via the queer Horoom Nights. In May 2018, armed police raided it; the response was a spontaneous techno 'rave-olution' protest outside parliament that made global headlines.",
    iconicSets: [
      "Ben Klock, Rødhåd and the Berlin techno elite who made Tbilisi a pilgrimage.",
 "Horoom Nights, the safe-space queer parties that are central to the club's meaning.",
      "The post-raid reopening night in 2018, charged with political defiance.",
    ],
 unique: "A club that doubles as a frontline for civil rights, the dancefloor as literal political battleground.",
    reputation: "The most politically significant club of its generation; uncompromising, defiant, and musically world-class.",
    secrets: "It's literally inside an old swimming pool under a stadium. The 2018 police raid backfired spectacularly, turning the club into an international symbol of freedom.",
  },
  "Stereo": {
    capacity: "≈ 750", founders: "Angel Moraes (sound design) · opened 1998",
    residencies: "Members' after-hours · Stereo resident program",
 lore: "Montreal's after-hours, alcohol-free members' temple is a sound-system pilgrimage. Built around a custom rig conceived by Angel Moraes, Stereo opens when other clubs close and runs deep into the next day for a crowd that comes purely for fidelity and the music. No bottles, no spectacle, just one of the most precise rooms on the continent.",
    iconicSets: [
      "Marathon after-hours sets that run well past sunrise to a connoisseur crowd.",
      "Deep, audiophile-focused house & techno where the sound system is the headliner.",
    ],
    unique: "An after-hours, no-alcohol, sound-first room engineered for fidelity above all else.",
 reputation: "A sound-system holy site, DJs and audiophiles cite it among the best-sounding rooms in the world.",
 secrets: "Being alcohol-free is the point, it keeps the focus on the music and the marathon. The custom system's tuning is the stuff of obsessive legend.",
  },
  "The Block": {
    capacity: "≈ 700", founders: "Opened 2010",
    residencies: "Resident-led techno program",
 lore: "Tucked beside Tel Aviv's central bus station, The Block is regularly named by touring DJs as one of the best-sounding rooms on earth. Israel's flagship techno club built its reputation almost entirely on fidelity and a devoted local crowd, proof a room can become world-famous on sound alone.",
    iconicSets: [
      "Visiting Berlin-axis techno greats who routinely call it a favorite room to play.",
      "Long resident-driven nights where the system's clarity is the draw.",
    ],
    unique: "A sound-system reputation so strong it put a city on the global techno map.",
    reputation: "A DJ-beloved sound pilgrimage and the anchor of Tel Aviv's serious scene.",
 secrets: "Its location by the bus station is unglamorous on purpose: everything went into the rig, not the lobby.",
  },
  "Concrete": {
    capacity: "≈ 600", founders: "Surpr!ze collective",
    residencies: "Extended/24h day-party program (2011–2019)",
 lore: "A barge moored on the Seine, Concrete rewired Parisian nightlife by winning the city's first extended/24-hour licenses, normalizing the marathon day-party in France. For most of the 2010s it was the most important room in Paris before closing in 2019, its influence directly shaping the city's current scene.",
    iconicSets: [
      "Marathon day-into-night boat sessions that broke Paris out of its 2am-closing habit.",
      "Underground house & techno bookings that made Paris a serious touring stop again.",
    ],
 unique: "It legally pried open Paris's clock, the club that made 24-hour clubbing French.",
    reputation: "A short but era-defining run; its DNA lives on across Parisian nightlife.",
 secrets: "Winning the extended-hours license was as important as any booking, it changed French nightlife policy.",
  },
  "Watergate": {
    capacity: "≈ 800 (two floors)", founders: "Opened 2002",
    residencies: "Watergate label nights",
 lore: "On the Spree by the Oberbaum Bridge, Watergate's lower 'Water Floor' opens onto the river with a wall of windows and an LED-strip ceiling: a more melodic, design-forward counterpoint to Berlin's brutalist rooms. A reliable engine of credible house and techno for two decades.",
    iconicSets: [
      "Riverbank sunrise sets watched through the floor-to-ceiling windows.",
      "Watergate label showcases that helped define a melodic Berlin house sound.",
    ],
 unique: "The river-level floor and LED ceiling, Berlin glamour without losing the music.",
    reputation: "A polished but credible Berlin mainstay; the accessible counterpoint to Berghain's severity.",
 secrets: "The Water Floor's windows open right onto the Spree, dawn over the river is the signature moment.",
  },
  "Nowadays": {
    capacity: "≈ 1,000 (indoor + large outdoor)", founders: "Justin Carter & Eamon Harkin (Mister Saturday Night)",
    residencies: "Mister Sunday · 'Nonstop' marathons",
 lore: "Built by the Mister Saturday/Sunday Night duo in Ridgewood, Queens, Nowadays brought a Berlin-grade ethos to New York: a huge tree-shaded backyard, a serious bespoke sound system, a no-phones-on-the-floor culture and community-first programming: including 'Nonstop,' marathon sessions that run for days.",
    iconicSets: [
 "Mister Sunday daytime parties: sunshine, families, and deep house in the backyard.",
      "'Nonstop' 24h+ marathon weekends with rotating residents and no headliner ego.",
    ],
 unique: "A New York club that prioritizes community, sound and a backyard over bottle service, and runs marathons most US cities can't.",
    reputation: "The standard-bearer for NYC's music-first revival; widely loved, deeply principled.",
    secrets: "The outdoor space and custom system were the whole investment thesis. Phones-down-on-the-floor is gently enforced to protect the vibe.",
  },
  "://about blank": {
    capacity: "≈ 900 (club + garden)", founders: "Collective-run since 2010",
    residencies: "Buttons · Homopatik · Cocktail d'Amore heritage",
 lore: "A collectively-run club on a former East Berlin railway site, ://about blank pairs serious techno with overt left-wing politics and one of the best club gardens in the city. Its parties (Buttons, Homopatik) are pillars of Berlin's queer and political nightlife, the dancefloor as community project.",
    iconicSets: [
      "Buttons and Homopatik nights central to Berlin's queer techno culture.",
      "Garden sessions in summer that run from afternoon deep into the next day.",
    ],
    unique: "Explicitly political, collectively run, with a garden that rivals the dancefloor.",
 reputation: "Berlin's conscience on the dancefloor: credible, inclusive, unafraid to take a stand.",
 secrets: "Profits and politics are intertwined, it openly supports antifascist and refugee causes. The garden is half the reason regulars come.",
  },
  "Sisyphos": {
    capacity: "≈ 5,000 across a sprawling site", founders: "Opened 2009 on a former dog-biscuit factory",
    residencies: "Weekend-long open-air program",
 lore: "On the grounds of an old dog-biscuit factory in Lichtenberg, Sisyphos is less a club than a small permanent festival: multiple floors, a lake, a beach, a 'Hammahalle,' all running from Friday night to Monday. It's the purest expression of Berlin's vibe-over-everything, anything-can-happen weekender culture.",
    iconicSets: [
      "Weekend-long open-air sets where DJs play to a sunrise-and-beyond crowd by the lake.",
      "The kind of unbilled, hours-deep b2bs that only happen when nobody's watching the clock.",
    ],
 unique: "A festival-sized playground that never really closes on the weekend: beach, lake, and endless floors.",
    reputation: "Berlin hedonism at its most free-spirited; less about lineups, all about atmosphere.",
 secrets: "There's an actual beach and lake on site. The door is famously vibe-based, they're reading whether you're there for the right reasons.",
  },
  "De School": {
    capacity: "≈ 900", founders: "Team behind Trouw (closed 2023)",
    residencies: "24-hour weekend program · concert hall + club",
 lore: "Opened in a former technical school by the Trouw crew, De School carried Amsterdam's 24-hour torch: a club, concert hall, gym and café that ran weekend-long with a famously discerning door and a no-photos floor. Though it closed in 2023, it set the standard for the city's serious underground.",
    iconicSets: [
      "Weekend-long sessions with the Berlin-axis techno elite in a no-phones room.",
      "Boiler-room-style intimacy with a strict door that protected the floor.",
    ],
 unique: "A 24h cultural complex, not just a club, and Amsterdam's most credible room of its era.",
    reputation: "Gone but revered; the benchmark the city still measures new clubs against.",
    secrets: "The building was a literal school. The closure was mourned scene-wide as the end of an era for Amsterdam.",
  },
  "Pacha": {
    capacity: "≈ 3,000", founders: "Ricardo Urgell (1973)",
    residencies: "Solomun +1 · Flower Power · historic Ibiza nights",
 lore: "The twin-cherry logo is the most recognizable in nightlife, and Pacha is Ibiza's grande dame: open since 1973, the farmhouse-turned-superclub that sold the island to the world. Solomun's +1 nights gave it genuine modern credibility, but its polished, table-service spectacle is exactly the commercialization this index marks down.",
    iconicSets: [
 "Solomun +1, the residency that restored real underground cred to Pacha in the 2010s.",
      "Decades of Flower Power nights, an Ibiza institution in their own right.",
    ],
 unique: "The most iconic brand in clubbing and genuine 1970s heritage, even if the modern model is glossy.",
 reputation: "Beloved and historic, but commercial, the famous cherries now sell as much as the music. On a music-integrity north star, that costs it.",
    secrets: "It began as a rural farmhouse club before Ibiza was Ibiza. The cherry logo is now a global fashion brand as much as a club.",
  },
  "Lux Frágil": {
    capacity: "≈ 1,000 (three floors + rooftop)", founders: "Manuel Reis (co-owned by John Malkovich)",
    residencies: "Lux resident program",
 lore: "Opened by legendary Lisbon promoter Manuel Reis, with actor John Malkovich as a co-owner, Lux sits in a converted riverside warehouse with a rooftop that catches the dawn over the Tagus. For 25+ years it has been the undisputed center of Lisbon nightlife and a key reason the city became a European clubbing destination.",
    iconicSets: ["Marathon house & techno nights that run to a rooftop sunrise over the river.", "Tastemaking bookings that made Lisbon a serious stop on the touring circuit."],
 unique: "A three-floor club topped by a rooftop terrace over the Tagus, the dawn view is the signature.",
    reputation: "Lisbon's defining institution and a tastemaker's favorite across Europe.",
 secrets: "Hollywood actor John Malkovich is a co-owner, a piece of trivia that delights first-timers.",
  },
  "Fuse": {
    capacity: "≈ 700", founders: "Peter Decuypere & team (1994)",
    residencies: "La Démence (queer party)",
 lore: "Belgium's longest-running techno club, in the Marolles district of Brussels, Fuse helped build the country's storied techno culture. In 2021 a single neighbor's noise complaint nearly shut it down: a global outcry and a citywide fight for nightlife saved it, making Fuse a symbol of clubbing's right to exist.",
 iconicSets: ["Early-'90s techno nights that seeded the Belgian scene.", "La Démence, one of Europe's most famous queer parties, calling Fuse home."],
    unique: "A 30-year techno institution that became a cause célèbre for nightlife rights.",
    reputation: "Belgium's techno HQ; beloved and fiercely defended by its city.",
    secrets: "One resident's noise complaint almost ended three decades of history in 2021.",
  },
  "Khidi": {
    capacity: "≈ 1,200", founders: "Opened 2016",
    residencies: "Khidi resident techno program",
 lore: "A raw, brutalist concrete labyrinth in Tbilisi that, alongside Bassiani, turned Georgia into a global techno pilgrimage after 2015. Two floors of unrelenting concrete and an uncompromising booking ethos make it a temple for the genre's hardcore.",
    iconicSets: ["Berlin-axis techno greats treating Tbilisi as a must-play.", "Marathon weekend sessions in the concrete halls."],
    unique: "Brutalist architecture and a no-compromise stance in a society where the scene is hard-won.",
    reputation: "One half of Tbilisi's world-famous techno pairing; defiant and serious.",
    secrets: "Part of the same scene targeted by the 2018 police raids that sparked Georgia's techno protests.",
  },
  "Corsica Studios": {
    capacity: "≈ 500 (two rooms)", founders: "Independent arts non-profit (2002)",
    residencies: "Hessle Audio & underground label nights",
    lore: "An independent, artist-run pair of railway-arch rooms in Elephant & Castle, Corsica is technically a non-profit arts organization. That independence has made it the cradle for London's most credible underground nights for two decades, free of corporate programming.",
    iconicSets: ["Theo Parrish and the deepest house/techno selectors in long arch sessions.", "Hessle Audio and bass-music label nights that shaped a London sound."],
    unique: "A non-profit arts charity that just happens to be one of London's best clubs.",
 reputation: "London's most credible small room, fiercely independent.",
    secrets: "It's run as a community arts space, which is why the programming never chases trends.",
  },
  "Nitsa": {
    capacity: "≈ 600", founders: "Inside Sala Apolo (1995)",
    residencies: "Nitsa resident program",
    lore: "Housed inside the historic 1940s Sala Apolo ballroom, Nitsa is Barcelona's longest-running electronic club and the serious counterweight to the city's Sónar-week tourist crush. A grand old theatre by day, a techno institution by night.",
    iconicSets: ["Jeff Mills and the techno canon in the old ballroom.", "Decades of credible house/techno that anchored Barcelona's scene."],
 unique: "A 1940s theatre turned techno temple, history you can feel in the architecture.",
    reputation: "Barcelona's credible core, beyond the festival-season hype.",
    secrets: "The grand old dance hall it lives in is nearly a century old.",
  },
  "Tenax": {
    capacity: "≈ 1,000", founders: "Opened 1981",
    residencies: "Nobody's Perfect (Saturdays)",
    lore: "One of Italy's oldest continuously running clubs, Tenax has survived decades of the country's notoriously restrictive nightlife laws. Its Saturday Nobody's Perfect residency is a national institution and the reason Florence stayed on the global house map.",
 iconicSets: ["The Nobody's Perfect Saturday series, one of Italy's longest-running house nights.", "International house & techno greats across four decades."],
 unique: "Italian longevity, a survivor in a country that's hard on clubs.",
    reputation: "Italy's enduring temple of house.",
    secrets: "It has outlasted countless waves of Italian anti-nightlife crackdowns.",
  },
  "Kompass Klub": {
    capacity: "≈ 1,800 (multi-room)", founders: "Opened 2015",
    residencies: "Kozzmozz heritage · resident techno",
    lore: "A former factory on the edge of Ghent that, within just a few years, became one of Europe's most respected techno destinations. Big industrial rooms, a serious system and Berlin-grade bookings made it the surprise heavyweight of Belgian clubbing.",
    iconicSets: ["Marathon techno nights drawing the Berlin axis to Ghent.", "Multi-room raves carrying Belgium's Kozzmozz rave lineage."],
    unique: "A raw factory complex that punched straight into Europe's top tier.",
    reputation: "Belgium's fast-rising techno powerhouse.",
    secrets: "It went from unknown to bucket-list in well under a decade.",
  },
  "Basement": {
    capacity: "≈ 600", founders: "Within the Knockdown Center (2019)",
    residencies: "no-phones techno program",
    lore: "A no-phones black box inside Queens' cavernous Knockdown Center, Basement is the most Berlin-minded room in New York. Stickered cameras, serious techno and a protected dancefloor brought the Berghain ethos to the US in a way few rooms dare.",
    iconicSets: ["Berlin techno residents bringing the no-photos marathon to NYC.", "Knockdown Center's huge adjoining space for festival-scale nights."],
 unique: "A genuine no-phones, music-first techno box, rare in camera-happy New York.",
    reputation: "NYC's most credible techno room.",
 secrets: "Phone cameras get stickered at the door, almost unheard of in the US.",
  },
  "D-Edge": {
    capacity: "≈ 1,000", founders: "Renato Ratier (2003)",
    residencies: "D-Edge resident program",
 lore: "Founded by Brazilian DJ Renato Ratier, D-Edge is a design-and-sound landmark, its LED-clad interior pulses with the music, that put São Paulo on the global electronic map. A room as obsessed with architecture and fidelity as with the dancefloor.",
    iconicSets: ["Sunrise techno sessions drawing the global circuit to Brazil.", "Resident-led nights showcasing São Paulo's deep scene."],
 unique: "An LED-reactive interior and serious sound, design as instrument.",
    reputation: "South America's flagship club.",
 secrets: "The LED lighting is synced to the music, the room itself is part of the show.",
  },
  "Womb": {
    capacity: "≈ 1,000 (four floors)", founders: "Opened 2000",
    residencies: "Womb resident program",
 lore: "Shibuya's four-floor mainstay, anchored by an enormous mirror ball and a serious sound system, Womb has been the hub of Tokyo's house and techno community for over two decades, a fixture of any global DJ's Japan tour.",
    iconicSets: ["Richie Hawtin and the global techno elite on the main floor.", "Multi-floor nights spanning house, techno and bass."],
    unique: "One of the largest mirror balls in clubbing, over four distinct floors.",
    reputation: "Tokyo's flagship electronic club.",
    secrets: "The giant mirror ball is a Shibuya landmark in its own right.",
  },
  "Kater Blau": {
    capacity: "≈ 1,000+ (riverside complex)", founders: "Bar25 / Katerholzig lineage (2014)",
    residencies: "weekend-long riverside program",
    lore: "The spiritual heir to the mythical Bar25, Kater Blau is a riverside Spree wonderland of driftwood whimsy, costumed regulars and weekenders that blur Friday into Monday. It carries the DNA of Berlin's most romanticized lost club.",
    iconicSets: ["Riverbank sessions that run for days in true Bar25 spirit.", "Costumed, anything-goes weekenders by the Spree."],
 unique: "Bar25's bloodline, fantastical décor and marathon riverside hedonism.",
    reputation: "Berlin vibes incarnate; less about lineups, all about the trip.",
    secrets: "Built from the crew and spirit of Bar25, the club Berlin still mourns.",
  },
  "Shelter": {
    capacity: "≈ 600", founders: "Under the A'DAM Tower (2014)",
    residencies: "Shelter techno program",
 lore: "A concrete bunker buried beneath the A'DAM Tower across the IJ from Amsterdam's center, Shelter is the city's no-frills underground anchor: no daylight, no distractions, just a serious room and a serious system.",
    iconicSets: ["Berlin-axis techno marathons in the windowless bunker.", "Long, dark, music-first sessions across the weekend."],
 unique: "A literal bunker under a tower, engineered for tunnel vision.",
    reputation: "Amsterdam's serious techno basement.",
 secrets: "There's no daylight by design, you lose all sense of time underground.",
  },
  "Warehouse Project": {
    capacity: "≈ 10,000 (seasonal, Depot Mayfield)", founders: "Sacha Lord & Sam Kandel (2006)",
    residencies: "Seasonal autumn–winter series",
    lore: "Not a permanent club but a seasonal autumn-to-NYE warehouse series that became a Manchester rite of passage. From the legendary Store Street railway tunnels to the cavernous Depot Mayfield, WHP turned a city's rave heritage into an annual institution.",
    iconicSets: ["The Store Street car-park-tunnel years now spoken of in mythic terms.", "Genre-spanning megabills that draw the whole UK to Manchester each winter."],
 unique: "A pop-up season, not a venue, scarcity is built into the model.",
    reputation: "A UK institution and Manchester's modern rave standard-bearer.",
    secrets: "It changes home venues; purists still argue the dripping Store Street tunnels were peak WHP.",
  },
  "FOLD": {
    capacity: "≈ 600", founders: "Opened 2018",
    residencies: "no-photos late-license program",
 lore: "A Canning Town industrial unit carrying the post-Berghain torch in London: no photos, a late license and a fiercely loyal, inclusive crowd. FOLD is where Londoners go when they want the marathon, music-first experience the city's tighter licensing usually denies.",
    iconicSets: ["Extended no-phones techno sessions that run far past last orders.", "Queer-friendly, community-minded marathons."],
    unique: "London's most committed no-phones, late-running room.",
    reputation: "The capital's most Berlin-like club.",
 secrets: "Cameras get covered at the door, a rarity that protects the floor's freedom.",
  },
  "Cocoricò": {
    capacity: "≈ 3,000", founders: "Opened 1989",
    residencies: "Historic Italian rave nights",
 lore: "A giant glass pyramid on the Adriatic riviera at Riccione, Cocoricò is a monument to Italy's '90s rave explosion: a vast, theatrical temple where a generation discovered techno and trance under the glass.",
    iconicSets: ["The '90s techno and trance nights that defined Italian rave culture.", "Theatrical productions under the iconic pyramid."],
 unique: "The glass pyramid: unmistakable, era-defining architecture.",
    reputation: "An Italian rave landmark, more heritage than cutting-edge today.",
    secrets: "It has weathered closures and financial dramas, but the pyramid keeps reopening.",
  },
  "Goa": {
    capacity: "≈ 1,500", founders: "Founded by Tristán/promoters (1997)",
    residencies: "Sunday morning sessions",
 lore: "Madrid's techno cornerstone, Goa is famous for its morning sessions, when the truly faithful keep dancing long past dawn while the rest of the city sleeps. A pillar of Spain's capital scene for over 25 years.",
    iconicSets: ["The legendary morning sessions running deep into Sunday daylight.", "Spanish and international techno across the decades."],
 unique: "Madrid's morning-after culture, Goa is where the night refuses to end.",
    reputation: "The capital's enduring techno HQ.",
    secrets: "The real Goa experience is the morning session, not the night.",
  },
  "Razzmatazz": {
    capacity: "≈ 3,500 (five rooms)", founders: "Opened 2000",
    residencies: "The Loft / Pop Bar resident nights",
 lore: "A five-room Poblenou megaclub where each space is its own world, from indie to techno. It's big and busy, but its electronic floors (The Loft especially) hold genuine credibility, making it Barcelona's everything-venue with a serious core.",
    iconicSets: ["The Loft's techno nights pulling international headliners.", "Five-rooms-one-ticket marathons across genres."],
    unique: "Five distinct clubs under one roof.",
 reputation: "Barcelona's biggest, credible where it counts.",
    secrets: "Each of the five rooms has its own loyal crowd and sound.",
  },
  "RSO": {
    capacity: "≈ 1,500", founders: "Opened 2019",
    residencies: "RSO resident techno",
 lore: "A riverside techno hangar in Berlin's Schöneweide that rapidly entered the city's serious-club conversation: a vast industrial space with a big system and the fewer-rules, marathon ethos Berlin is built on.",
    iconicSets: ["Big-room techno marathons in the riverside hangar.", "Berlin-axis residents and a 24h weekend rhythm."],
 unique: "A huge industrial hangar by the water, scale plus Berlin freedom.",
    reputation: "New-generation Berlin techno.",
    secrets: "It earned its stripes fast in the world's most demanding techno city.",
  },
  "Bossa Nova Civic Club": {
    capacity: "≈ 200", founders: "Opened 2012",
    residencies: "resident-led house & techno",
 lore: "Bushwick's beloved tropical-themed sweatbox: tiny, unpretentious and entirely scene-defining. 'Bossa' is where New York's underground actually hangs out, and it survived a 2015 fire only to come back stronger.",
    iconicSets: ["Resident-driven house/techno where locals, not tourists, set the tone.", "The packed, no-ego nights that define Brooklyn's underground."],
    unique: "Tiny, tropical, and the genuine living room of NYC's underground.",
    reputation: "A Brooklyn institution punching far above its 200 capacity.",
    secrets: "A 2015 fire gutted it; the community rebuilt and it never lost its soul.",
  },
  "Vent": {
    capacity: "≈ 500", founders: "Contact/Air lineage (2016)",
    residencies: "sound-first techno program",
 lore: "A deliberately understated, sound-obsessed Omotesando room born from Tokyo's revered Contact/Air lineage. No spectacle, no flash, just one of the best-tuned systems in the city and the connoisseur's choice in Tokyo.",
    iconicSets: ["Minimal and techno selectors drawn by the room's fidelity.", "Late, music-only sessions for Tokyo's serious heads."],
    unique: "Sound above everything, in a city of spectacle.",
    reputation: "Tokyo's connoisseur techno room.",
 secrets: "It keeps a low profile on purpose, the music is the only marketing.",
  },
  "Warung Beach Club": {
    capacity: "≈ 3,000", founders: "Opened 2002",
    residencies: "Warung Day Party · sunrise sessions",
    lore: "A wooden, Balinese-inspired temple on Brazil's southern coast, Warung turns the beach and the sunrise into a global bucket-list experience for melodic house and techno. Architecture, ocean and sound fuse into one of the world's most beautiful rooms.",
    iconicSets: ["Sunrise sets over the Atlantic that top many a DJ's career-highlight list.", "Marathon day parties blending the beach into the booth."],
 unique: "A beachfront wooden temple, the sea and the sunrise are part of the design.",
    reputation: "Brazil's flagship destination club.",
 secrets: "The Bali-inspired architecture is open to the ocean, the dawn light is the headliner.",
  },
  "Phonox": {
    capacity: "≈ 500", founders: "Opened 2016",
    residencies: "single-resident Saturdays",
    lore: "Brixton's residency-driven room runs a singular model: one resident DJ per long Saturday night, all season. That format has incubated and broken credible new names (HAAi's residency among the most famous) and made Phonox a true talent factory.",
    iconicSets: ["HAAi's season-long Saturday residency that broke her internationally.", "Long single-DJ sets where a resident builds the whole night."],
 unique: "One resident, all night, all season, a residency model almost no one else commits to.",
    reputation: "London's incubator for the next credible names.",
 secrets: "The single-resident format is the whole point, it forges artists in real time.",
  },
  "Public Records": {
    capacity: "≈ 250", founders: "Shane Davis & Francis Harris (2019)",
    residencies: "hi-fi listening + club program",
 lore: "A Gowanus sound-room obsessed with fidelity and design, Public Records treats audio as the entire experience, from daytime hi-fi listening sessions to late club nights, all on a meticulously tuned, music-first system.",
    iconicSets: ["Audiophile listening sessions that double as deep-house education.", "Late club nights where the room's tuning is the draw."],
 unique: "Hi-fi obsession over spectacle, the sound system is the headliner.",
    reputation: "NYC's audiophile temple.",
 secrets: "The room and rig were designed by sound obsessives, every surface is tuned.",
  },
  "Halcyon": {
    capacity: "≈ 250", founders: "Opened 2015",
    residencies: "deep-house resident program",
    lore: "San Francisco's intimate Funktion-One room keeps the city's deep-house heritage alive in a post-warehouse, tech-boom era that hasn't been kind to nightlife. Small, warm and sound-obsessed, it's SF's credible holdout.",
    iconicSets: ["Deep-house resident nights for SF's loyal faithful.", "Hi-fi sessions prioritizing warmth and fidelity."],
    unique: "A Funktion-One hi-fi room flying the flag for SF house in a tough nightlife city.",
    reputation: "San Francisco's most credible small club.",
    secrets: "It's a deep-house holdout in a city that's lost many of its rooms.",
  },
  "Flash": {
    capacity: "≈ 350 (multi-level)", founders: "Opened 2014",
    residencies: "techno resident program",
    lore: "A purpose-built, sound-led club anchoring Washington DC's techno community. Designed from the ground up around the system and the floor, Flash gave the capital a serious, music-first room of international standard.",
    iconicSets: ["Techno residents and Berlin-axis guests in the main room.", "Rooftop-to-basement nights spanning the building."],
 unique: "Built for sound, floor-up, not a converted space.",
    reputation: "DC's techno home.",
    secrets: "Its multi-level design lets one ticket feel like several clubs.",
  },
  "La Cheetah": {
    capacity: "≈ 200", founders: "Opened 2010",
    residencies: "underground house/techno residents",
    lore: "Glasgow's intimate basement keeps the city's revered underground lineage alive alongside the Sub Club. Tiny, dark and devoted to the music, it's a connoisseur's room in a city that takes its dancing very seriously.",
    iconicSets: ["Deep underground house & techno for Glasgow's faithful.", "Intimate guest sets that sell out instantly."],
    unique: "A ~200-capacity basement built entirely on intimacy and taste.",
    reputation: "Glasgow's connoisseur room beneath the street.",
 secrets: "Capacity is tiny by design, getting in feels like a secret.",
  },
  "Bloc": {
    capacity: "≈ 700", founders: "Bloc rave/festival brand (2007)",
    residencies: "Bloc parties",
 lore: "Rooted in the legendary Bloc warehouse-rave and festival brand, the London club carries a serious sound-system reputation. The brand's infamy is sealed by the 2012 Bloc Weekend: shut down on its opening night for overcrowding, one of UK rave's most notorious moments.",
    iconicSets: ["Bloc parties showcasing leftfield electronic and bass.", "The mythologized (and chaotic) Bloc Weekend festivals."],
    unique: "Warehouse-rave heritage and a sound-first reputation.",
    reputation: "UK underground cred, with a notorious streak.",
 secrets: "Bloc Weekend 2012 was shut on opening night for overcrowding, UK rave infamy.",
  },
  "Spazio 900 / Goa Roma": {
    capacity: "≈ 1,000", founders: "Giancarlino (Goa Club, 1995)",
    residencies: "Ultrabeat · resident techno",
    lore: "Rome's enduring techno outpost, founded by scene legend Giancarlino, has kept the capital's faithful dancing for decades. A serious room in a city where credible techno had to fight for space.",
    iconicSets: ["Italian and international techno across nearly three decades.", "Resident nights that built Rome's underground."],
 unique: "Rome's longevity, a credible techno home in the Eternal City.",
    reputation: "The capital's techno HQ.",
    secrets: "Founder Giancarlino is a revered figure in Italian dance music.",
  },
  "Salon zur Wilden Renate": {
    capacity: "≈ 600 (multi-room maze)", founders: "Opened 2007",
    residencies: "weekend-long program · hidden rooms",
    lore: "A labyrinthine former apartment building of secret rooms, hidden bars, a mirror maze and a 'house of love,' Renate is quintessential whimsical Berlin hedonism. Part club, part funhouse, it rewards the curious who go looking for what's behind the next door.",
    iconicSets: ["Marathon weekenders that wander through the building's many rooms.", "House and techno across a warren of intimate floors."],
 unique: "A maze of secret rooms and hidden corners, exploration is the experience.",
    reputation: "Berlin's playful, surreal side.",
 secrets: "There's a hidden mirror maze (Irrgarten) and rooms you have to find, not everyone does.",
  },
  "Hï Ibiza": {
    capacity: "≈ 5,000", founders: "Ushuaïa Entertainment (2017)",
    residencies: "Black Coffee · Eric Prydz [CELL] · Glitterbox",
 lore: "Built on the hallowed former site of the old Space, Hï is the slick, state-of-the-art face of modern commercial Ibiza, repeatedly voted the world's #1 club by DJ Mag. It's polished, enormous and brilliantly produced: and precisely the spectacle-first, mainstream model this index is built to discount.",
    iconicSets: ["Black Coffee's marquee Saturday residency.", "Eric Prydz's [CELL] audiovisual production pushing club tech to its limit."],
 unique: "Cutting-edge production, including a DJ booth inside the unisex 'Wash Room' toilets.",
    reputation: "Commercially dominant and award-laden, but credibility-light by a music-integrity north star.",
 secrets: "There's a working DJ booth inside the bathrooms (the Wash Room), and it's built on the grave of the legendary Space.",
  },
};
