// Auto-generated by backend/fetchClubImages.js - Wikimedia lead images (freely licensed).
// Clubs without a confident match use the designed gradient cover.
export const CLUB_IMAGES = {
  "Club Space": "https://upload.wikimedia.org/wikipedia/commons/7/72/Club_Space_Logo.png",
  "Amnesia": "https://upload.wikimedia.org/wikipedia/commons/9/99/Amnesia_ibiza.jpeg",
  "Berghain / Panorama Bar": "https://upload.wikimedia.org/wikipedia/commons/8/8c/Berlin_Berghain.jpg",
  "Tresor": "https://upload.wikimedia.org/wikipedia/commons/6/69/Tresor_logo.png",
  "fabric": "https://upload.wikimedia.org/wikipedia/commons/4/4c/Fabric_Club_London_2020.jpg",
  "Bassiani": "https://upload.wikimedia.org/wikipedia/en/c/cb/%E1%83%93%E1%83%98%E1%83%9C%E1%83%90%E1%83%9B%E1%83%9D_%E1%83%90%E1%83%A0%E1%83%94%E1%83%9C%E1%83%90-Dinamo_Arena_01.jpg",
  "Fuse": "https://upload.wikimedia.org/wikipedia/commons/1/1e/Fuse_blaasstraat.jpg",
  "De School": "https://upload.wikimedia.org/wikipedia/commons/6/60/De_School_Dancefloor.jpg",
  "Warehouse Project": "https://upload.wikimedia.org/wikipedia/commons/3/38/Exterior_of_Manchester_Mayfield.jpg",
  "Cocoricò": "https://upload.wikimedia.org/wikipedia/commons/f/f2/Discoteca_Cocoric%C3%B2_Riccione_35.jpg",
  "Razzmatazz": "https://upload.wikimedia.org/wikipedia/commons/b/be/Salida_de_Razzmatazz.JPG",
  "Public Records": "https://upload.wikimedia.org/wikipedia/commons/5/56/The_Westerlies_at_Public_Records%2C_June_2025.jpg"
};
